# Generated by Django 3.2.5 on 2021-07-11 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dataConnector', '0007_remove_candle_prediction_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval', models.CharField(choices=[('1m', '1m'), ('3m', '3m'), ('5m', '5m'), ('15m', '15m'), ('30m', '30m'), ('1h', '1h'), ('2h', '2h'), ('4h', '4h'), ('6h', '6h'), ('8h', '8h'), ('12h', '12h'), ('1d', '1d'), ('3d', '3d'), ('1w', '1w'), ('1M', '1M')], max_length=3)),
                ('prediction_model', models.CharField(max_length=200)),
                ('prediction_time', models.DateTimeField()),
                ('close_time', models.BigIntegerField()),
                ('predicted_y', models.DecimalField(decimal_places=8, max_digits=14)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataConnector.exchangeinfo')),
            ],
        ),
    ]
