# Generated by Django 3.2.5 on 2021-07-12 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataConnector', '0007_remove_candle_prediction_type'),
        ('Predictor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predicteddata',
            name='interval',
        ),
        migrations.RemoveField(
            model_name='predicteddata',
            name='prediction_model',
        ),
        migrations.RemoveField(
            model_name='predicteddata',
            name='prediction_time',
        ),
        migrations.RemoveField(
            model_name='predicteddata',
            name='symbol',
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('interval', models.CharField(choices=[('1m', '1m'), ('3m', '3m'), ('5m', '5m'), ('15m', '15m'), ('30m', '30m'), ('1h', '1h'), ('2h', '2h'), ('4h', '4h'), ('6h', '6h'), ('8h', '8h'), ('12h', '12h'), ('1d', '1d'), ('3d', '3d'), ('1w', '1w'), ('1M', '1M')], max_length=3)),
                ('prediction_model', models.CharField(max_length=200)),
                ('prediction_time', models.DateTimeField()),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataConnector.exchangeinfo')),
            ],
            options={
                'get_latest_by': 'open_time',
                'unique_together': {('symbol', 'interval', 'prediction_model', 'prediction_time')},
            },
        ),
        migrations.AddField(
            model_name='predicteddata',
            name='prediction',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Predictor.prediction'),
            preserve_default=False,
        ),
    ]
