# Generated by Django 3.2 on 2021-05-27 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cryptocurrency',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=10, unique=True)),
                ('rank', models.IntegerField()),
                ('is_new', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('type', models.CharField(choices=[('coin', 'coin'), ('token', 'token')], max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeInfo',
            fields=[
                ('symbol', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=20)),
                ('base_asset_precision', models.IntegerField(default='0')),
                ('quote_precision', models.IntegerField(default='0')),
                ('quote_asset_precision', models.IntegerField(default='0')),
                ('base_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_assets', to='dataConnector.cryptocurrency')),
                ('quote_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_assets', to='dataConnector.cryptocurrency')),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_change', models.DecimalField(decimal_places=8, max_digits=14)),
                ('price_change_percent', models.DecimalField(decimal_places=8, max_digits=14)),
                ('weighted_avg_price', models.DecimalField(decimal_places=8, max_digits=14)),
                ('prev_close_price', models.DecimalField(decimal_places=8, max_digits=14)),
                ('last_price', models.DecimalField(decimal_places=8, max_digits=14)),
                ('last_qty', models.DecimalField(decimal_places=8, max_digits=14)),
                ('bid_price', models.DecimalField(decimal_places=8, max_digits=14)),
                ('ask_price', models.DecimalField(decimal_places=8, max_digits=14)),
                ('open_price', models.DecimalField(decimal_places=8, max_digits=14)),
                ('high_price', models.DecimalField(decimal_places=8, max_digits=14)),
                ('low_price', models.DecimalField(decimal_places=8, max_digits=14)),
                ('volume', models.DecimalField(decimal_places=8, max_digits=14)),
                ('quote_volume', models.DecimalField(decimal_places=8, max_digits=14)),
                ('open_time', models.BigIntegerField()),
                ('close_time', models.BigIntegerField()),
                ('first_id', models.IntegerField()),
                ('last_id', models.IntegerField()),
                ('count', models.IntegerField()),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataConnector.exchangeinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Candle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval', models.CharField(max_length=3)),
                ('open_time', models.BigIntegerField(default='0')),
                ('open', models.DecimalField(decimal_places=8, default='0', max_digits=14)),
                ('high', models.DecimalField(decimal_places=8, default='0', max_digits=14)),
                ('low', models.DecimalField(decimal_places=8, default='0', max_digits=14)),
                ('close', models.DecimalField(decimal_places=8, default='0', max_digits=14)),
                ('volume', models.DecimalField(decimal_places=8, default='0', max_digits=14)),
                ('close_time', models.BigIntegerField(default='0')),
                ('quote_asset_volume', models.DecimalField(decimal_places=8, default='0', max_digits=14)),
                ('number_of_trades', models.IntegerField(default='0')),
                ('taker_buy_base_asset_volume', models.DecimalField(decimal_places=8, default='0', max_digits=14)),
                ('taker_buy_quote_asset_volume', models.DecimalField(decimal_places=8, default='0', max_digits=14)),
                ('is_real', models.BooleanField(default=True)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataConnector.exchangeinfo')),
            ],
            options={
                'unique_together': {('symbol', 'interval', 'open_time', 'close_time', 'is_real')},
            },
        ),
    ]
