# Generated by Django 3.0.5 on 2021-04-11 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cryptocurrency',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=4)),
                ('rank', models.IntegerField()),
                ('type', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('P', 'Portion')], max_length=5)),
            ],
        ),
    ]
