# Generated by Django 3.2 on 2021-05-12 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataConnector', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchangeinfo',
            name='server_time',
        ),
        migrations.RemoveField(
            model_name='exchangeinfo',
            name='timezone',
        ),
        migrations.AlterField(
            model_name='exchangeinfo',
            name='base_asset',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='exchangeinfo',
            name='quote_asset',
            field=models.CharField(max_length=20),
        ),
    ]
