# Generated by Django 3.2 on 2021-06-01 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataConnector', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candle',
            options={'get_latest_by': 'open_time'},
        ),
        migrations.AlterField(
            model_name='candle',
            name='close',
            field=models.DecimalField(decimal_places=8, max_digits=14),
        ),
        migrations.AlterField(
            model_name='candle',
            name='close_time',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='candle',
            name='high',
            field=models.DecimalField(decimal_places=8, max_digits=14),
        ),
        migrations.AlterField(
            model_name='candle',
            name='interval',
            field=models.CharField(choices=[('1m', '1m'), ('3m', '3m'), ('5m', '5m'), ('15m', '15m'), ('30m', '30m'), ('1h', '1h'), ('2h', '2h'), ('4h', '4h'), ('6h', '6h'), ('8h', '8h'), ('12h', '12h'), ('1d', '1d'), ('3d', '3d'), ('1w', '1w'), ('1M', '1M')], max_length=3),
        ),
        migrations.AlterField(
            model_name='candle',
            name='low',
            field=models.DecimalField(decimal_places=8, max_digits=14),
        ),
        migrations.AlterField(
            model_name='candle',
            name='number_of_trades',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='candle',
            name='open',
            field=models.DecimalField(decimal_places=8, max_digits=14),
        ),
        migrations.AlterField(
            model_name='candle',
            name='open_time',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='candle',
            name='quote_asset_volume',
            field=models.DecimalField(decimal_places=8, max_digits=14),
        ),
        migrations.AlterField(
            model_name='candle',
            name='taker_buy_base_asset_volume',
            field=models.DecimalField(decimal_places=8, max_digits=14),
        ),
        migrations.AlterField(
            model_name='candle',
            name='taker_buy_quote_asset_volume',
            field=models.DecimalField(decimal_places=8, max_digits=14),
        ),
        migrations.AlterField(
            model_name='candle',
            name='volume',
            field=models.DecimalField(decimal_places=8, max_digits=14),
        ),
    ]
