# Generated by Django 3.2 on 2021-05-21 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataConnector', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candle',
            name='interval',
            field=models.CharField(max_length=30),
        ),
    ]
