# Generated by Django 3.2 on 2021-04-29 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataConnector', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='close_time',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='rate',
            name='open_time',
            field=models.BigIntegerField(),
        ),
    ]
