# Generated by Django 3.0.5 on 2021-04-11 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataConnector', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptocurrency',
            name='type',
            field=models.CharField(choices=[('C', 'coin'), ('T', 'token')], max_length=5),
        ),
    ]
