# Generated by Django 3.2 on 2021-05-22 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataConnector', '0002_alter_candle_interval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptocurrency',
            name='id',
            field=models.CharField(max_length=75, primary_key=True, serialize=False),
        ),
    ]
