# Generated by Django 3.2 on 2021-04-29 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataConnector', '0002_auto_20210429_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='symbol',
            field=models.CharField(max_length=20),
        ),
    ]
