# Generated by Django 3.2 on 2021-05-01 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataConnector', '0003_alter_rate_symbol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rate',
            name='id',
        ),
        migrations.AlterField(
            model_name='rate',
            name='symbol',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
