# Generated by Django 3.0.5 on 2021-04-11 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataConnector', '0003_auto_20210411_1824'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='cryptocurrency',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cryptocurrency',
            name='is_new',
            field=models.BooleanField(default=False),
        ),
    ]
