# Generated by Django 3.2 on 2021-05-22 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataConnector', '0004_alter_cryptocurrency_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptocurrency',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
