# Generated by Django 3.0.5 on 2021-04-11 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataConnector', '0004_auto_20210411_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptocurrency',
            name='is_active',
            field=models.BooleanField(),
        ),
    ]
