# Generated by Django 3.2 on 2021-05-22 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataConnector', '0005_alter_cryptocurrency_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptocurrency',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
