# Generated by Django 3.0.5 on 2021-04-11 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataConnector', '0006_auto_20210411_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptocurrency',
            name='type',
            field=models.CharField(choices=[('coin', 'coin'), ('token', 'token')], max_length=5),
        ),
    ]
